$(document).ready(function(){
    $('.slider').bxSlider({
        auto:true,
    });
    $('.owl-carousel').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:true
            },
            600:{
                items:2,
                nav:false
            },
            1000:{
                items:,
                nav:true,
                loop:false
            },
            1300:{
                items:3,
                nav:true,
                loop:false
            },
            1500:{
                items:4,
                nav:true,
                loop:false
            },
            2000:{
                items:3,
                nav:true,
                loop:false
            }
            
        }
    })
});